### PR TITLE
Report detailed version constraints info

### LINKED ISSUE #17: Bubble up errors from TFE configuration issues
I was having issues setting up TFE with the provider, only realised what the issue was when I did a debug

```
2018/09/14 15:25:03 [2018-09-14T15:25:03.909+0100 [DEBUG] plugin.terraform-provider-tfe_v0.1.0_x4: 2018/09/14 15:25:03 [DEBUG] Service discovery for ptfe.petems.xyz at https://ptfe.petems.xyz/.well-known/terraform.json
2018-09-14T15:25:04.323+0100 [DEBUG] plugin.terraform-provider-tfe_v0.1.0_x4: 2018/09/14 15:25:04 [WARN] Failed to request discovery document: Get https://ptfe.petems.xyz/.well-known/terraform.json: x509: certificate signed by unknown authority
```

`certificate signed by unknown authority` would be a nicer error to show, rather than ``provider.tfe: host ptfe.petems.xyz does not provide a Terraform Enterprise API``

### PR DESCRIPTION
**Pull request by svanharmelen**
This PR fixes #17 and improves the UX by returning more detailed error messages. This code is duplicated from the remote backend to make sure the behavior and returned errors are consistent.

### CODE REVIEW

File: tfe/provider.go [hunk 1]
```diff
@@ -221,6 +251,111 @@ func credentialsSource(config *Config) auth.CredentialsSource {
 	return creds
 }
 
+// checkConstraints checks service version constrains against our own
+// version and returns rich and informational diagnostics in case any
+// incompatibilities are detected.
+func checkConstraints(c *disco.Constraints) error {
```
Comment (radeksimko) [inline tfe/provider.go]: It would be nice to have a test for this, but it's not a blocker.

File: tfe/provider.go [hunk 2]
```diff
@@ -113,30 +113,60 @@ func providerConfigure(d *schema.ResourceData) (interface{}, error) {
...
 
-	// Check if we were able to discover a service address.
-	if address == nil {
-		return nil, fmt.Errorf("host %s does not provide a Terraform Enterprise API", host)
+	if providerVersion.ProviderVersion != "dev" {
+		// We purposefully ignore the error and return the previous error, as
+		// checking for version constraints is considered optional.
+		constraints, _ := host.VersionConstraints(tfeServiceIDs[0], "tfe-provider")
+
+		// First check any contraints we might have received.
```
Comment (radeksimko) [inline tfe/provider.go]: 👀 typo `contraints` -> `constraints`

File: tfe/provider.go (hunk 1 above)
Comment (svanharmelen) [reply tfe/provider.go]: Yeah agree, so added a test for it.
